# Generated by Django 3.1.4 on 2020-12-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'تولید کننده',
                'verbose_name_plural': 'تولید کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوع ها',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اثر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='effect/', verbose_name='تصویر')),
                ('vote', models.IntegerField(default=0)),
                ('is_exist', models.BooleanField(default=True, verbose_name='موجود')),
                ('select', models.CharField(default='effect', max_length=100)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calture.producer', verbose_name='تولید کننده')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calture.subject', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'اثر',
                'verbose_name_plural': 'آثار',
                'ordering': ['-vote'],
            },
        ),
    ]
